spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  servlet:
    multipart:
        enabled: true
        max-file-size: 10MB
        max-request-size: 10MB
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/dbms
    username: siddeshwar
    password: sM62Ahm5>J:+<9}D-y"d#u
    driver-class-name: com.mysql.cj.jdbc.Driver
